version: "3.9"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
        POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  pgAdmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"