import { type Config } from "tailwindcss";

export default {
    content: ["./src/**/*.{js,ts,jsx,tsx}"],
    theme: {
        extend: {},
    },
    plugins: [],
    safelist: [
        "text-[#2596be]",
        "text-[#1a8cd8]",
        "text-[#849099]",
        "text-[#eff3f4]",
        "text-[#e8f5fe]",
        "text-[#e6e7e7]",
        "bg-[#2596be]",
        "bg-[#1a8cd8]",
        "bg-[#849099]",
        "bg-[#eff3f4]",
        "bg-[#e8f5fe]",
        "bg-[#e6e7e7]",
        "hover:text-[#2596be]",
        "hover:text-[#1a8cd8]",
        "hover:text-[#849099]",
        "hover:text-[#eff3f4]",
        "hover:text-[#e8f5fe]",
        "hover:text-[#e6e7e7]",
        "hover:bg-[#2596be]",
        "hover:bg-[#1a8cd8]",
        "hover:bg-[#849099]",
        "hover:bg-[#eff3f4]",
        "hover:bg-[#e8f5fe]",
        "hover:bg-[#e6e7e7]",
    ],
} satisfies Config;
