import React from "react";
import Header from "next/head";
const Head = () => {
    return (
        <Header>
            <title>Create T3 App</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Header>
    );
};

export default Head;
